<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitfenrir
{
    public static $prefixLengthsPsr4 = array (
        'I' => 
        array (
            'Itembase\\' => 9,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Itembase\\' => 
        array (
            0 => __DIR__ . '/..' . '/itembase/psdk2/src',
            1 => __DIR__ . '/..' . '/itembase/psdk2-ext-data/src',
            2 => __DIR__ . '/..' . '/itembase/m1-ext-data/src',
            3 => __DIR__ . '/..' . '/itembase/m1-ext-multishop/src',
            4 => __DIR__ . '/..' . '/itembase/m1-ext-platform/src',
            5 => __DIR__ . '/..' . '/itembase/m1-ext-storage/src',
            6 => __DIR__ . '/..' . '/itembase/psdk2-ext-remotefs/src',
            7 => __DIR__ . '/..' . '/itembase/psdk2-ext-signup/src',
            8 => __DIR__ . '/..' . '/itembase/psdk2-ext-sysinfo/src',
        ),
    );

    public static $prefixesPsr0 = array (
        'I' => 
        array (
            'Itembase\\Composer' => 
            array (
                0 => __DIR__ . '/..' . '/itembase/composer-platform-ext-installer/src',
            ),
        ),
    );

    public static $classMap = array (
        'Itembase\\Composer\\Installer' => __DIR__ . '/..' . '/itembase/composer-platform-ext-installer/src/Itembase/Composer/Installer.php',
        'Itembase\\Composer\\PlatformInstaller\\AbstractInstaller' => __DIR__ . '/..' . '/itembase/composer-platform-ext-installer/src/Itembase/Composer/PlatformInstaller/AbstractInstaller.php',
        'Itembase\\Composer\\PlatformInstaller\\Magento' => __DIR__ . '/..' . '/itembase/composer-platform-ext-installer/src/Itembase/Composer/PlatformInstaller/Magento.php',
        'Itembase\\Composer\\PlatformInstaller\\Prestashop' => __DIR__ . '/..' . '/itembase/composer-platform-ext-installer/src/Itembase/Composer/PlatformInstaller/Prestashop.php',
        'Itembase\\Composer\\PlatformInstaller\\Woocommerce' => __DIR__ . '/..' . '/itembase/composer-platform-ext-installer/src/Itembase/Composer/PlatformInstaller/Woocommerce.php',
        'Itembase\\PluginExtension\\Data\\Extension' => __DIR__ . '/..' . '/itembase/m1-ext-data/src/Itembase/PluginExtension/Data/Extension.php',
        'Itembase\\PluginExtension\\Multishop\\Extension' => __DIR__ . '/..' . '/itembase/m1-ext-multishop/src/Itembase/PluginExtension/Multishop/Extension.php',
        'Itembase\\PluginExtension\\Multishop\\Multishop' => __DIR__ . '/..' . '/itembase/m1-ext-multishop/src/Itembase/PluginExtension/Multishop/Multishop.php',
        'Itembase\\PluginExtension\\Platform\\Extension' => __DIR__ . '/..' . '/itembase/m1-ext-platform/src/Itembase/PluginExtension/Platform/Extension.php',
        'Itembase\\PluginExtension\\Platform\\Platform' => __DIR__ . '/..' . '/itembase/m1-ext-platform/src/Itembase/PluginExtension/Platform/Platform.php',
        'Itembase\\PluginExtension\\Storage\\Extension' => __DIR__ . '/..' . '/itembase/m1-ext-storage/src/Itembase/PluginExtension/Storage/Extension.php',
        'Itembase\\PluginExtension\\Storage\\Storage' => __DIR__ . '/..' . '/itembase/m1-ext-storage/src/Itembase/PluginExtension/Storage/Storage.php',
        'Itembase\\PsdkExtension\\Data\\Extension' => __DIR__ . '/..' . '/itembase/psdk2-ext-data/src/Itembase/PsdkExtension/Data/Extension.php',
        'Itembase\\PsdkExtension\\Data\\FetcherInterface' => __DIR__ . '/..' . '/itembase/psdk2-ext-data/src/Itembase/PsdkExtension/Data/FetcherInterface.php',
        'Itembase\\PsdkExtension\\Registration\\PingHandler' => __DIR__ . '/..' . '/itembase/psdk2/src/Itembase/Psdk/Core/PingHandler.php',
        'Itembase\\PsdkExtension\\RemoteFS\\Extension' => __DIR__ . '/..' . '/itembase/psdk2-ext-remotefs/src/Itembase/PsdkExtension/RemoteFS/Extension.php',
        'Itembase\\PsdkExtension\\RemoteFS\\Filesystem' => __DIR__ . '/..' . '/itembase/psdk2-ext-remotefs/src/Itembase/PsdkExtension/RemoteFS/Filesystem.php',
        'Itembase\\PsdkExtension\\Signup\\Extension' => __DIR__ . '/..' . '/itembase/psdk2-ext-signup/src/Itembase/PsdkExtension/Signup/Extension.php',
        'Itembase\\PsdkExtension\\SysInfo\\Extension' => __DIR__ . '/..' . '/itembase/psdk2-ext-sysinfo/src/Itembase/PsdkExtension/SysInfo/Extension.php',
        'Itembase\\Psdk\\Container\\ContainerAwareInterface' => __DIR__ . '/..' . '/itembase/psdk2/src/Itembase/Psdk/Container/ContainerAwareInterface.php',
        'Itembase\\Psdk\\Container\\ServiceContainer' => __DIR__ . '/..' . '/itembase/psdk2/src/Itembase/Psdk/Container/ServiceContainer.php',
        'Itembase\\Psdk\\Core' => __DIR__ . '/..' . '/itembase/psdk2/src/Itembase/Psdk/Core.php',
        'Itembase\\Psdk\\Core\\ExceptionHandler' => __DIR__ . '/..' . '/itembase/psdk2/src/Itembase/Psdk/Core/ExceptionHandler.php',
        'Itembase\\Psdk\\Core\\Logger' => __DIR__ . '/..' . '/itembase/psdk2/src/Itembase/Psdk/Core/Logger.php',
        'Itembase\\Psdk\\Core\\OAuthClient' => __DIR__ . '/..' . '/itembase/psdk2/src/Itembase/Psdk/Core/OAuthClient.php',
        'Itembase\\Psdk\\Event\\EventAwareInterface' => __DIR__ . '/..' . '/itembase/psdk2/src/Itembase/Psdk/Event/EventAwareInterface.php',
        'Itembase\\Psdk\\Event\\EventDispatcher' => __DIR__ . '/..' . '/itembase/psdk2/src/Itembase/Psdk/Event/EventDispatcher.php',
        'Itembase\\Psdk\\Event\\EventListenerInterface' => __DIR__ . '/..' . '/itembase/psdk2/src/Itembase/Psdk/Event/EventListenerInterface.php',
        'Itembase\\Psdk\\Extension\\ExtensionInterface' => __DIR__ . '/..' . '/itembase/psdk2/src/Itembase/Psdk/Extension/ExtensionInterface.php',
        'Itembase\\Psdk\\Extension\\ExtensionsLoader' => __DIR__ . '/..' . '/itembase/psdk2/src/Itembase/Psdk/Extension/ExtensionsLoader.php',
        'Itembase\\Psdk\\Http\\HttpClient' => __DIR__ . '/..' . '/itembase/psdk2/src/Itembase/Psdk/Http/HttpClient.php',
        'Itembase\\Psdk\\Http\\HttpHandler' => __DIR__ . '/..' . '/itembase/psdk2/src/Itembase/Psdk/Http/HttpHandler.php',
        'Itembase\\Psdk\\Http\\Request' => __DIR__ . '/..' . '/itembase/psdk2/src/Itembase/Psdk/Http/Request.php',
        'Itembase\\Psdk\\Http\\RequestAwareInterface' => __DIR__ . '/..' . '/itembase/psdk2/src/Itembase/Psdk/Http/RequestAwareInterface.php',
        'Itembase\\Psdk\\Http\\Response' => __DIR__ . '/..' . '/itembase/psdk2/src/Itembase/Psdk/Http/Response.php',
        'Itembase\\Psdk\\Http\\ResponseAwareInterface' => __DIR__ . '/..' . '/itembase/psdk2/src/Itembase/Psdk/Http/ResponseAwareInterface.php',
        'Itembase\\Psdk\\Platform\\Frontend\\ControllerInterface' => __DIR__ . '/..' . '/itembase/psdk2/src/Itembase/Psdk/Platform/Frontend/ControllerInterface.php',
        'Itembase\\Psdk\\Platform\\MultiShop\\MultishopAbstract' => __DIR__ . '/..' . '/itembase/psdk2/src/Itembase/Psdk/Platform/MultiShop/MultishopAbstract.php',
        'Itembase\\Psdk\\Platform\\MultiShop\\Shop' => __DIR__ . '/..' . '/itembase/psdk2/src/Itembase/Psdk/Platform/MultiShop/Shop.php',
        'Itembase\\Psdk\\Platform\\PlatformInterface' => __DIR__ . '/..' . '/itembase/psdk2/src/Itembase/Psdk/Platform/PlatformInterface.php',
        'Itembase\\Psdk\\Platform\\StorageInterface' => __DIR__ . '/..' . '/itembase/psdk2/src/Itembase/Psdk/Platform/StorageInterface.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitfenrir::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitfenrir::$prefixDirsPsr4;
            $loader->prefixesPsr0 = ComposerStaticInitfenrir::$prefixesPsr0;
            $loader->classMap = ComposerStaticInitfenrir::$classMap;

        }, null, ClassLoader::class);
    }
}
