<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname(dirname($vendorDir));

return array(
    'Itembase\\' => array($vendorDir . '/itembase/psdk2/src', $vendorDir . '/itembase/psdk2-ext-data/src', $vendorDir . '/itembase/m1-ext-data/src', $vendorDir . '/itembase/m1-ext-multishop/src', $vendorDir . '/itembase/m1-ext-platform/src', $vendorDir . '/itembase/m1-ext-storage/src', $vendorDir . '/itembase/psdk2-ext-remotefs/src', $vendorDir . '/itembase/psdk2-ext-signup/src', $vendorDir . '/itembase/psdk2-ext-sysinfo/src'),
);
